function replaceCalculatedOperator(
  _match: string,
  leftRaw: string,
  rightRaw: string,
  resultRaw: string
): string {
  const left = Number(leftRaw.replace(",", "."));
  const right = Number(rightRaw.replace(",", "."));
  const result = Number(resultRaw.replace(",", "."));

  if (Number.isFinite(left) && Number.isFinite(right) && Number.isFinite(result)) {
    if (right !== 0 && Math.abs(left / right - result) < 0.001) {
      return `${leftRaw} ÷ ${rightRaw} = ${resultRaw}`;
    }
    if (Math.abs(left * right - result) < 0.001) {
      return `${leftRaw} × ${rightRaw} = ${resultRaw}`;
    }
  }

  return `${leftRaw} × ${rightRaw} = ${resultRaw}`;
}

export function repairVisibleText(text: string): string {
  const isVolume = /\bvolume\b|\bV\s*=/i.test(text);
  const isAngleText = /\bangle\b|\bangles\b|\btriangle\b|\bmesure\b|\bsomme\b|\\circ/i.test(text);
  const isMoneyText = /\bprix\b|co[uû]t|euros?|€|achat|d[ée]pense|montant|r[ée]duction|augmentation/i.test(text);
  const isLengthContext = /construire un triangle|triangle de c.t.s|longueur|distance|segment|p.rim.tre/i.test(text);
  const hasAmbiguousCmUnit = /cm\s*\?/.test(text);
  const hasAmbiguousMUnit = /m\s*\?/.test(text);

  return text
    .replace(/Ã€/g, "À")
    .replace(/Ã‰/g, "É")
    .replace(/Ã©/g, "é")
    .replace(/Ã¨/g, "è")
    .replace(/Ãª/g, "ê")
    .replace(/Ã«/g, "ë")
    .replace(/Ã /g, "à")
    .replace(/Ã¢/g, "â")
    .replace(/Ã®/g, "î")
    .replace(/Ã´/g, "ô")
    .replace(/Ã»/g, "û")
    .replace(/Ã¹/g, "ù")
    .replace(/Ã§/g, "ç")
    .replace(/Â°/g, "°")
    .replace(/Ï€/g, "π")
    .replace(/([A-Za-zÀ-ÿ])\s\?\s([A-Za-zÀ-ÿ])/g, "$1?$2")
    .replace(/([A-Za-zÀ-ÿ])\s\?/g, "$1?")
    .replace(/\?\s([A-Za-zÀ-ÿ])/g, "?$1")
    .replace(/\bn\?gatif/gi, (match) => match[0] === "N" ? "Négatif" : "négatif")
    .replace(/\bn\?gatifs/gi, (match) => match[0] === "N" ? "Négatifs" : "négatifs")
    .replace(/Priorit\?/g, "Priorité")
    .replace(/priorit\?/g, "priorité")
    .replace(/Parenth\?ses/g, "Parenthèses")
    .replace(/parenth\?se/g, "parenthèse")
    .replace(/\?tapes/g, "étapes")
    .replace(/Compl\?ter/g, "Compléter")
    .replace(/compl\?ter/g, "compléter")
    .replace(/Compl\?te/g, "Complète")
    .replace(/compl\?te/g, "complète")
    .replace(/compl\?ment/g, "complément")
    .replace(/d\?cimal/g, "décimal")
    .replace(/D\?cimal/g, "Décimal")
    .replace(/d\?cimale/g, "décimale")
    .replace(/unit\?/g, "unité")
    .replace(/unit\?s/g, "unités")
    .replace(/dixi\?me/g, "dixième")
    .replace(/dixi\?mes/g, "dixièmes")
    .replace(/\?gale/g, "égale")
    .replace(/\?gales/g, "égales")
    .replace(/\?crire/g, "écrire")
    .replace(/\?cris/g, "écris")
    .replace(/repr\?sente/g, "représente")
    .replace(/repr\?sentent/g, "représentent")
    .replace(/num\?rateur/g, "numérateur")
    .replace(/num\?rateurs/g, "numérateurs")
    .replace(/d\?nominateur/g, "dénominateur")
    .replace(/d\?nominateurs/g, "dénominateurs")
    .replace(/quantit\?/g, "quantité")
    .replace(/co\?te/g, "coûte")
    .replace(/co\?tent/g, "coûtent")
    .replace(/poss\?de/g, "possède")
    .replace(/pav\?/g, "pavé")
    .replace(/ar\?te/g, "arête")
    .replace(/ar\?tes/g, "arêtes")
    .replace(/arri\?re/g, "arrière")
    .replace(/sym\?trie/g, "symétrie")
    .replace(/m\?me/g, "même")
    .replace(/m\?diatrice/g, "médiatrice")
    .replace(/C\?t\?s/g, "Côtés")
    .replace(/c\?t\?s/g, "côtés")
    .replace(/c\?t\?/g, "côté")
    .replace(/oppos\?/g, "opposé")
    .replace(/parall\?logramme/g, "parallélogramme")
    .replace(/parall\?le/g, "parallèle")
    .replace(/parall\?les/g, "parallèles")
    .replace(/p\?rim\?tre/g, "périmètre")
    .replace(/cons\?cutif/g, "consécutif")
    .replace(/cons\?cutifs/g, "consécutifs")
    .replace(/suppl\?mentaire/g, "supplémentaire")
    .replace(/suppl\?mentaires/g, "supplémentaires")
    .replace(/coordonn\?e/g, "coordonnée")
    .replace(/coordonn\?es/g, "coordonnées")
    .replace(/envoy\?/g, "envoyé")
    .replace(/donn\?/g, "donné")
    .replace(/diff\?rence/g, "différence")
    .replace(/sup\?rieur/g, "supérieur")
    .replace(/sup\?rieurs/g, "supérieurs")
    .replace(/sup\?rieure/g, "supérieure")
    .replace(/inf\?rieur/g, "inférieur")
    .replace(/inf\?rieurs/g, "inférieurs")
    .replace(/inf\?rieure/g, "inférieure")
    .replace(/apr\?s/g, "après")
    .replace(/r\?le/g, "rôle")
    .replace(/rep\?re/g, "repère")
    .replace(/rempla\?ant/g, "remplaçant")
    .replace(/conna\?t/g, "connaît")
    .replace(/cliqu\?/g, "cliqué")
    .replace(/d\?signe/g, "désigne")
    .replace(/extr\?mit/g, "extrémit")
    .replace(/g\?om\?trie/g, "géométrie")
    .replace(/r\?f\?rence/g, "référence")
    .replace(/r\?gle/g, "règle")
    .replace(/m\?thode/g, "méthode")
    .replace(/s\?cante/g, "sécante")
    .replace(/s\?cantes/g, "sécantes")
    .replace(/r\?ductions/g, "réductions")
    .replace(/r\?duit/g, "réduit")
    .replace(/r\?duits/g, "réduits")
    .replace(/r\?p\?t\?/g, "répété")
    .replace(/d\?cale/g, "décale")
    .replace(/homoth\?tie/g, "homothétie")
    .replace(/carr\?/g, "carré")
    .replace(/D\?placement/g, "Déplacement")
    .replace(/d\?plac\?/g, "déplacé")
    .replace(/premi\?re/g, "première")
    .replace(/centim\?tres/g, "centimètres")
    .replace(/R\?soudre/g, "Résoudre")
    .replace(/r\?soudre/g, "résoudre")
    .replace(/R\?duire/g, "Réduire")
    .replace(/r\?duire/g, "réduire")
    .replace(/D\?velopper/g, "Développer")
    .replace(/d\?velopper/g, "développer")
    .replace(/D\?terminer/g, "Déterminer")
    .replace(/d\?terminer/g, "déterminer")
    .replace(/litt\?rale/g, "littérale")
    .replace(/mon\?me/g, "monôme")
    .replace(/mon\?mes/g, "monômes")
    .replace(/z\?ro/g, "zéro")
    .replace(/M\?diane/g, "Médiane")
    .replace(/m\?diane/g, "médiane")
    .replace(/\?tendue/g, "étendue")
    .replace(/Fr\?quence/g, "Fréquence")
    .replace(/fr\?quence/g, "fréquence")
    .replace(/probabilit\?/g, "probabilité")
    .replace(/\?v\?nement/g, "événement")
    .replace(/lin\?aire/g, "linéaire")
    .replace(/ant\?c\?dent/g, "antécédent")
    .replace(/ordonn\?e/g, "ordonnée")
    .replace(/v\?rifie/g, "vérifie")
    .replace(/hypot\?nuse/g, "hypoténuse")
    .replace(/trigonom\?trie/g, "trigonométrie")
    .replace(/trigonom\?trique/g, "trigonométrique")
    .replace(/r\?p\?tition/g, "répétition")
    .replace(/r\?p\?ter/g, "répéter")
    .replace(/r\?p\?te/g, "répète")
    .replace(/r\?ponse/g, "réponse")
    .replace(/r\?sultat/g, "résultat")
    .replace(/gagn\?/g, "gagné")
    .replace(/moiti\?/g, "moitié")
    .replace(/r\?ussissent/g, "réussissent")
    .replace(/\?quilibr\?/g, "équilibré")
    .replace(/\?quation/g, "équation")
    .replace(/Equation/g, "Équation")
    .replace(/R\?duction/g, "Réduction")
    .replace(/r\?duction/g, "réduction")
    .replace(/pr\?alable/g, "préalable")
    .replace(/(\d+(?:[,.]\d+)?) \? (\d+(?:[,.]\d+)?) = (\d+(?:[,.]\d+)?)/g, replaceCalculatedOperator)
    .replace(/(\d+(?:[,.]\d+)?) \? 100/g, "$1 ÷ 100")
    .replace(/(\d+(?:[,.]\d+)?) \?(?=[,.]|$)/g, (_match, amount: string) => isMoneyText ? `${amount} €` : `${amount} ?`)
    .replace(/(\d+(?:[,.]\d+)?) \?(?=\s*(?:et|:|-))/g, "$1°")
    .replace(/longueur \? largeur \? hauteur/gi, "longueur × largeur × hauteur")
    .replace(/longueur \? largeur/gi, "longueur × largeur")
    .replace(/base \? hauteur/gi, "base × hauteur")
    .replace(/v = d \? t/gi, "v = d ÷ t")
    .replace(/\b([A-Z]) = ([^=.]+?) \? ([^=.]+?)\./g, "$1 = $2 × $3.")
    .replace(/\bcm\?/g, isVolume ? "cm³" : "cm²")
    .replace(/\bm\?/g, isVolume ? "m³" : "m²")
    .replace(/cm2/g, "cm²")
    .replace(/cm3/g, "cm³")
    .replace(/m2/g, "m²")
    .replace(/m3/g, "m³")
    .replace(/(\d)\?/g, "$1°")
    .replace(/(\d+(?:[,.]\d+)?) €/g, isAngleText ? "$1°" : "$1 €")
    .replace(/(vaut \d+(?:[,.]\d+)?) €/gi, "$1 ?")
    .replace(/\$\s*(\d+(?:[,.]\d+)?)\s+\?vaut/gi, "$$1 vaut")
    .replace(/\?partir/gi, "À partir")
    .replace(/\?OA/g, "× OA")
    .replace(/\?n\b/g, "à n")
    .replace(/\?x\b/g, "à x")
    .replace(/\?resultat\b/gi, "à résultat")
    .replace(/resultaténombre/gi, "résultat = nombre")
    .replace(/résultat à ([0-9]+) à x/gi, "résultat = $1 × x")
    .replace(/résultat = nombre à ([0-9]+)/gi, "résultat = nombre × $1")
    .replace(/\$\s+\?\s*\$/g, "$?$")
    .replace(/\$\s+\?/g, "$?")
    .replace(/\\times\?/g, "\\times ?")
    .replace(/\\times\s+\?/g, "\\times ?")
    .replace(/\\dfrac\{\s+\?/g, "\\dfrac{?")
    .replace(/\{\s+\?\s+\}/g, "{ ? }")
    .replace(/ \? (?=(calculer|la|le|l'|une|un|des|ce|cet|cette|partir|quelle|quoi|\d)\b)/gi, " à ")
    .replace(/([A-Za-zÀ-ÿ])\?(?=\s*(?:\d|:))/g, "$1 à")
    .replace(/\?(?=(la|le|l'|un|une|des|de|d'|à|a)\b)/gi, " à ")
    .replace(/([A-Za-zÀ-ÿ])\?([A-Za-zÀ-ÿ])/g, "$1é$2")
    .replace(/\bDonne\s*:\s*e\s*:\s*/gi, "Donne : ")
    .replace(/\bDonne\s*:\s*e\b/gi, "Donne")
    .replace(/moitiéde/gi, "moitié de")
    .replace(/Onécrit/gi, "On écrit")
    .replace(/onécrit/gi, "on écrit")
    .replace(/longueurségales/gi, "longueurs égales")
    .replace(/partségales/gi, "parts égales")
    .replace(/Inégalitétriangulaire/gi, "Inégalité triangulaire")
    .replace(/inégalitétriangulaire/gi, "inégalité triangulaire")
    .replace(/unitépartagée/gi, "unité partagée")
    .replace(/pavédroit/gi, "pavé droit")
    .replace(/côtéadjacent/gi, "côté adjacent")
    .replace(/côtéopposé/gi, "côté opposé")
    .replace(/opposéet/gi, "opposé et")
    .replace(/Probabilit à/gi, "Probabilité ")
    .replace(/probabilit à/gi, "probabilité ")
    .replace(/Unévénement/gi, "Un événement")
    .replace(/estéquelle/gi, "est à quelle")
    .replace(/correspond donc \?/gi, "correspond donc à")
    .replace(/quadrilatére/gi, "quadrilatère")
    .replace(/troisiéme/gi, "troisième")
    .replace(/Aprés/gi, "Après")
    .replace(/extrémites/gi, "extrémités")
    .replace(/designent/gi, "désignent")
    .replace(/designe/gi, "désigne")
    .replace(/geometrie/gi, "géométrie")
    .replace(/decrit/gi, "décrit")
    .replace(/consecutifs/gi, "consécutifs")
    .replace(/hypotenuse/gi, "hypoténuse")
    .replace(/lineaire/gi, "linéaire")
    .replace(/coordonnees/gi, "coordonnées")
    .replace(/repetitions/gi, "répétitions")
    .replace(/Resultat/gi, "Résultat")
    .replace(/carre/gi, "carré")
    .replace(/cotes/gi, "côtés")
    .replace(/egales/gi, "égales")
    .replace(/egaux/gi, "égaux")
    .replace(/parallelogramme/gi, "parallélogramme")
    .replace(/opposees/gi, "opposées")
    .replace(/opposes/gi, "opposés")
    .replace(/pave/gi, "pavé")
    .replace(/parentheses/gi, "parenthèses")
    .replace(/extremites/gi, "extrémités")
    .replace(/appelees/gi, "appelées")
    .replace(/exterieur/gi, "extérieur")
    .replace(/depart/gi, "départ")
    .replace(/determinent/gi, "déterminent")
    .replace(/secantes/gi, "sécantes")
    .replace(/appartient a\b/gi, "appartient à")
    .replace(/n est pas/gi, "n'est pas")
    .replace(/\. écris/g, ". Écris")
    .replace(/superieur/gi, "supérieur")
    .replace(/inferieur/gi, "inférieur")
    .replace(/consecutif/gi, "consécutif")
    .replace(/mediane/gi, "médiane")
    .replace(/est multiplie par/gi, "est multiplié par")
    .replace(/critere/gi, "critère")
    .replace(/divisibilite/gi, "divisibilité")
    .replace(/irreductible/gi, "irréductible")
    .replace(/equivalente/gi, "équivalente")
    .replace(/equivalent/gi, "équivalent")
    .replace(/reversible/gi, "réversible")
    .replace(/scientifique/gi, "scientifique")
    .replace(/ecriture/gi, "écriture")
    .replace(/equilibre/gi, "équilibre")
    .replace(/deplacement/gi, "déplacement")
    .replace(/initialisee/gi, "initialisée")
    .replace(/imbriquee/gi, "imbriquée")
    .replace(/conditionnel/gi, "conditionnel")
    .replace(/(\d)(?=(?:mm|cm|dm|dam|hm|km|mg|cg|dg|dag|hg|kg|mL|cL|dL|L|€)(?:²|³|\b))/g, "$1 ")
    .replace(/(\d)(?=m(?:²|³|\b))/g, "$1 ")
    .replace(/(\d)(?=(?:élève|personne|fois|pas|minute|seconde|objet|boule|article|côté|part|valeur|point|sommet|arête|face|heure|jour)s?\b)/gi, "$1 ")
    .replace(/\\to\?/g, "\\to ?")
    .replace(/\bdonné (?=\$?\d|\$?[A-Za-zÀ-ÿ])/g, "donne ")
    .replace(/cm²/g, isLengthContext && hasAmbiguousCmUnit ? "cm" : "cm²")
    .replace(/m²/g, isLengthContext && hasAmbiguousMUnit ? "m" : "m²")
    .replace(/([A-Za-zÀ-ÿ])\?(?=\s|$)/g, "$1 ?")
    .replace(/\s{2,}/g, " ")
    .trim();
}

